name       : shortwave
version    : 3.2.0
release    : 1
source     :
    - https://gitlab.gnome.org/World/Shortwave/-/archive/3.2.0/Shortwave-3.2.0.tar.gz : e7a0fb3a49c200cb125e17d54c8e04e7f1aca40321935ff436f92269b4e912d5
homepage   : https://gitlab.gnome.org/World/Shortwave
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Shortwave is an internet radio player that provides access to a station database with over 30,000 stations.
description: |
    Shortwave is an internet radio player that provides access to a station database with over 30,000 stations.
networking : yes
builddeps  :
    - cargo
    - pkgconfig(libadwaita-1)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(shumate-1.0)
    - pkgconfig(sqlite3)
setup      : |
    sed -i "/vcs_tag/c\vcs_tag    = '%version%'" meson.build
    %patch -p1 -i $pkgfiles/0001-dont-need-post-install-steps.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
