name       : sway
version    : 1.6.1
release    : 20
source     :
    - https://github.com/swaywm/sway/archive/refs/tags/1.6.1.tar.gz : 8b138867cd83217de07138144b1279fe58e0421eb10c91122aa33c8770fe7391
license    : MIT
component  : desktop
summary    : sway is an i3-compatible Wayland compositor
description: |
    sway is an i3-compatible Wayland compositor
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libevdev)
    - pkgconfig(libcap)
    - pkgconfig(pango)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wlroots)
rundeps    :
    - swaylock
setup      : |
    %meson_configure -Dgdk-pixbuf=enabled -Dxwayland=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/sway.desktop $installdir/usr/share/xsessions/sway.desktop
