name       : zoxide
version    : 0.8.0
release    : 1
source     :
    - https://github.com/ajeetdsouza/zoxide/archive/refs/tags/v0.8.0.tar.gz : 111c5f1cd92b1cb54e2f0a801003098a601c653ec5a378f3d0ea1c9659854477
license    : MIT
homepage   : https://github.com/ajeetdsouza/zoxide
component  : system.utils
summary    : zoxide is a smarter cd command, inspired by z and autojump
description: |
    zoxide is a smarter cd command, inspired by z and autojump
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/zoxide $installdir/usr/bin/zoxide
