name       : ox
version    : 0.2.7
release    : 2
source     :
    - https://github.com/curlpipe/ox/archive/0.2.7.tar.gz : ae08c18243b66d8c24f9e0844e499890be2864584a8d3e38f186fdf3aa5c09fc
license    : GPL-2.0-or-later
component  : editor
summary    : Ox is a terminal text editor with IDE-like features written in Rust
description: |
    Ox is a terminal text editor with IDE-like features written in Rust
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build
install    : |
    install -Dm00755 $workdir/target/debug/ox $installdir/usr/bin/ox
