name       : television
version    : 0.9.2
release    : 1
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.9.2.tar.gz : 93f82f33e699a4a91f0015d88856a7fde5ae95bfa132a02c08518ddd264256cb
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
