name       : television
version    : 0.11.7
release    : 11
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.11.7.tar.gz : d3687a286b4813ab8534d7ce8653908dcf17ad291bc865f3f64c183163f0b650
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
