name       : television
version    : 0.10.6
release    : 6
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.10.6.tar.gz : d316ddd82aa725e381f238aec190423c6dd1569b25697a3e318fef990205ade3
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
