name       : television
version    : 0.10.3
release    : 5
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.10.3.tar.gz : b1df3632463982f203ac8682534f1e34729c7d635aab7dc45bca4877b56f2585
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
