name       : television
version    : 0.15.3
release    : 21
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.15.3.tar.gz : 5097343a03ed140ef643e5dfcceb48a77f9c372dbd3d043d523e25f9c4016deb
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
