name       : television
version    : 0.14.5
release    : 18
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.14.5.tar.gz : 6bffabdcd03672ec014bd9a3f6a262d01eed0127df8a308a1b060a68c7580704
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
