name       : television
version    : 0.10.2
release    : 4
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.10.2.tar.gz : fb85884a7684323872e895271969695dc4ddc3ef7550aad3cc76504fd9df21cd
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
