name       : television
version    : 0.10.0
release    : 3
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.10.0.tar.gz : 62dbc15b4109be90ef7bda6993523223aa6f89f39333ea8d35d515edc4ccb98d
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
