name       : television
version    : 0.15.9
release    : 25
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.15.9.tar.gz : 5f46cbe7b14e1d6e3958f436b1d6ed8af86e9914d7d2aee5a9379e8e1772072d
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
