name       : television
version    : 0.15.6
release    : 23
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.15.6.tar.gz : fe527628b313dbb4a5d3f2518bfb1b8b4969bd7d91822c216ca3de294010f0d7
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
