name       : television
version    : 0.15.0
release    : 19
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.15.0.tar.gz : 379573f0d45cc03abb71174c4e76b4e875500fb67df511bb1c106d814417fdd5
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
