name       : television
version    : 0.9.3
release    : 2
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.9.3.tar.gz : dc2f55c14875abf9958f543ecfd250c2631bc00302b7fb717d54b87686a3cb2d
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
