name       : television
version    : 0.10.7
release    : 7
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.10.7.tar.gz : 39a490a394a0ce975b1144c775acb1bb53e29383cd0ebf023ed7c2b66ad96d88
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
