name       : television
version    : 0.15.2
release    : 20
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.15.2.tar.gz : 36c97916d7062025697e6268992985e0e7c7f0b458230faaca3735d09c911cca
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
