name       : television
version    : 0.11.5
release    : 10
source     :
    - https://github.com/alexpasmantier/television/archive/refs/tags/0.11.5.tar.gz : 6f74edd1a37cd41ea5a1ec0137699013f816e8c9d16338da31f0381ae2cd553a
homepage   : https://github.com/alexpasmantier/television
license    : MIT
component  : programming.tools
summary    : Television is a fast and versatile fuzzy finder TUI
description: |
    Television is a fast and versatile fuzzy finder TUI
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tv
