name       : tlpui
version    : 1.3.1
release    : 1
source     :
    - https://github.com/d4nj1/TLPUI/archive/tlpui-1.3.1.tar.gz : 3e1781287d0f6dece3817d727e79679ebb29115e706d1c5137192fef1920a71e
license    : GPL-2.0-or-later
component  : system.utils
summary    : A GTK-UI to change TLP configuration files easily
description: |
    A GTK-UI to change TLP configuration files easily
rundeps    :
    - tlp

    
build      : |
    %python3_setup
install    : |
    %python3_install
