name       : wlsunset
version    : 0.4.0
release    : 3
source     :
    - https://git.sr.ht/~kennylevinsen/wlsunset/archive/0.4.0.tar.gz : a86ffb1793fe622802ec25795b69df864715986ecc175f7734e739c9e264ed72
license    : MIT
homepage   : https://git.sr.ht/~kennylevinsen/wlsunset
component  : desktop
summary    : Day/night gamma adjustments for Wayland compositors supporting wlr-gamma-control-unstable-v1
description: |
    Day/night gamma adjustments for Wayland compositors supporting wlr-gamma-control-unstable-v1.
builddeps  :
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-scanner)
setup      : |
    %meson_configure
build      : |2

    %ninja_build
install    : |
    %ninja_install

