name       : wlsunset
version    : 0.1.0
release    : 1
source     :
    - https://git.sr.ht/~kennylevinsen/wlsunset/archive/0.1.0.tar.gz : 78ec889f74505aa2f9060eebdee05092bda5452104656c0d868b2f0a4998f53c
license    : MIT
component  : desktop
summary    : Day/night gamma adjustments for Wayland compositors supporting wlr-gamma-control-unstable-v1
description: |
    Day/night gamma adjustments for Wayland compositors supporting wlr-gamma-control-unstable-v1.
builddeps  :
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-scanner)
setup      : |
    %meson_configure
build      : |

    %ninja_build
install    : |
    %ninja_install

