name       : amfora
version    : 1.8.0
release    : 1
source     :
    - https://github.com/makeworld-the-better-one/amfora/archive/v1.8.0.tar.gz : 2cf95009ee9b70e46f92ea6346d4f615df2c163b27182ec0e62bf67fb9f9544c
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : Gemini client for the terminal
description: |
    Amfora aims to be the best looking Gemini client with the most features, all in the terminal.
homepage   : https://github.com/makeworld-the-better-one/amfora
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 $workdir/amfora $installdir/usr/bin/amfora
    install -Dm00644 $workdir/amfora.desktop $installdir/usr/share/applications/amfora.desktop
