name       : spdlog
version    : 1.8.5
release    : 3
source     :
    - https://github.com/gabime/spdlog/archive/refs/tags/v1.8.5.tar.gz : 944d0bd7c763ac721398dca2bb0f3b5ed16f67cef36810ede5061f35a543b4b8
license    : MIT
homepage   : https://github.com/gabime/spdlog
component  : programming.library
summary    : Fast C++ logging library
description: |
    Fast C++ logging library
setup      : |
    %cmake_ninja \
        -DSPDLOG_BUILD_BENCH=OFF \
        -DSPDLOG_BUILD_EXAMPLES=OFF \
        -DSPDLOG_BUILD_SHARED=ON \
        -DSPDLOG_BUILD_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
