name       : gtk-layer-shell
version    : 0.6.0
release    : 3
source     :
    - https://github.com/wmww/gtk-layer-shell/archive/refs/tags/v0.6.0.tar.gz : 9a0ba72cea90e092d6b10ba47e627cd873271d287d9af80a6f66ab131fb34cac
license    : GPL-3.0-or-later
component  : desktop
summary    : A library to write GTK applications that use Layer Shell. Layer Shell is a Wayland protocol for desktop shell components.
description: |
    A library to write GTK applications that use Layer Shell. Layer Shell is a Wayland protocol for desktop shell components.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-wayland-3.0)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-scanner)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
