name       : eisvogel
version    : 3.3.0
release    : 9
source     :
    - https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v3.3.0/Eisvogel-3.3.0.tar.gz : 0eb287d299e73aa884d0b35fa27a28ae326afa04f51959e54f01cbbe76601489
license    : BSD-3-Clause
homepage   : https://github.com/Wandmalfarbe/pandoc-latex-template
component  : office
summary    : Eisvogel LaTeX template + a directory watcher script
description: |
    Eisvogel LaTex template + a directory watcher script
rundeps    :
    - pandoc
    - texlive-all
install    : |
    install -Dm00644 $workdir/eisvogel.latex $installdir/usr/share/eisvogel/eisvogel.tex
    install -Dm00755 $pkgfiles/eis $installdir/usr/bin/eis
    install -Dm00755 $pkgfiles/eis-new $installdir/usr/bin/eis-new
