name       : eisvogel
version    : 3.1.0
release    : 7
source     :
    - https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v3.1.0/Eisvogel-3.1.0.tar.gz : 167bf78fbbd131161bb4b395db28924b6621ac6d9e661c7acdba8bc17e0a773f
license    : BSD-3-Clause
homepage   : https://github.com/Wandmalfarbe/pandoc-latex-template
component  : office
summary    : Eisvogel LaTeX template + a directory watcher script
description: |
    Eisvogel LaTex template + a directory watcher script
rundeps    :
    - pandoc
    - texlive-all
install    : |
    install -Dm00644 $workdir/eisvogel.latex $installdir/usr/share/eisvogel/eisvogel.tex
    install -Dm00755 $pkgfiles/eis $installdir/usr/bin/eis
    install -Dm00755 $pkgfiles/eis-new $installdir/usr/bin/eis-new
