name       : eisvogel
version    : 3.4.0
release    : 10
source     :
    - https://github.com/Wandmalfarbe/pandoc-latex-template/archive/refs/tags/v3.4.0.tar.gz : 17b24fa49de5653878d500e61a04cfa89568e2d40e961674acb3551ce77a038b
license    : BSD-3-Clause
homepage   : https://github.com/Wandmalfarbe/pandoc-latex-template
component  : office
summary    : Eisvogel LaTeX template + a directory watcher script
description: |
    Eisvogel LaTex template + a directory watcher script
rundeps    :
    - pandoc
    - texlive-all
install    : |
    install -Dm00644 -t $installdir/usr/share/eisvogel $workdir/template-multi-file/*.latex 
    install -Dm00755 $pkgfiles/eis $installdir/usr/bin/eis
    install -Dm00755 $pkgfiles/eis-new $installdir/usr/bin/eis-new
    %install_license LICENSE
