name       : eisvogel
version    : 2.4.2
release    : 4
source     :
    - https://github.com/Wandmalfarbe/pandoc-latex-template/archive/refs/tags/2.4.2.tar.gz : b1115bdf1ea03ac1d47299265251da9834c4646acbc83158bcc7c61c38379c1a
license    : BSD-3-Clause
component  : office
summary    : Eisvogel LaTeX template + a directory watcher script
description: |
    Eisvogel LaTex template + a directory watcher script
rundeps    :
    - pandoc
    - texlive-all
install    : |
    install -Dm00644 $workdir/eisvogel.tex $installdir/usr/share/eisvogel/eisvogel.tex
    install -Dm00755 $pkgfiles/eis $installdir/usr/bin/eis
    install -Dm00755 $pkgfiles/eis-new $installdir/usr/bin/eis-new
