name       : eisvogel
version    : 2.5.0
release    : 5
source     :
    - https://github.com/Wandmalfarbe/pandoc-latex-template/archive/refs/tags/v2.5.0.tar.gz : acb5680544ee6da68d920d559797ab33e16c27f6f249bbc381d5e3640b0a68ce
license    : BSD-3-Clause
component  : office
summary    : Eisvogel LaTeX template + a directory watcher script
description: |
    Eisvogel LaTex template + a directory watcher script
rundeps    :
    - pandoc
    - texlive-all
install    : |
    install -Dm00644 $workdir/eisvogel.tex $installdir/usr/share/eisvogel/eisvogel.tex
    install -Dm00755 $pkgfiles/eis $installdir/usr/bin/eis
    install -Dm00755 $pkgfiles/eis-new $installdir/usr/bin/eis-new
