name       : eisvogel
version    : 3.2.1
release    : 8
source     :
    - https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v3.2.1/Eisvogel-3.2.1.tar.gz : 8e95113596fa672ab426b1c6cdca0255b08be94cde7c2eea010809d84085d177
license    : BSD-3-Clause
homepage   : https://github.com/Wandmalfarbe/pandoc-latex-template
component  : office
summary    : Eisvogel LaTeX template + a directory watcher script
description: |
    Eisvogel LaTex template + a directory watcher script
rundeps    :
    - pandoc
    - texlive-all
install    : |
    install -Dm00644 $workdir/eisvogel.latex $installdir/usr/share/eisvogel/eisvogel.tex
    install -Dm00755 $pkgfiles/eis $installdir/usr/bin/eis
    install -Dm00755 $pkgfiles/eis-new $installdir/usr/bin/eis-new
