name       : atomicparsley
version    : 20221229
release    : 1
source     :
    - https://github.com/wez/atomicparsley/archive/refs/tags/20221229.172126.d813aa6.tar.gz : 2f095a251167dc771e8f4434abe4a9c7af7d8e13c718fb8439a0e0d97078899b
homepage   : https://github.com/wez/atomicparsley
license    : GPL-2.0-or-later
component  : multimedia.dunno
summary    : AtomicParsley is a lightweight command line program for reading, parsing and setting metadata into MPEG-4 files, in particular, iTunes-style metadata
description: |
    AtomicParsley is a lightweight command line program for reading, parsing and setting metadata into MPEG-4 files, in particular, iTunes-style metadata
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
