name       : wlroots
version    : 0.12.0
release    : 6
source     :
    - git|https://github.com/swaywm/wlroots.git : c740fccc9dd0913908c0632c10f8c6d10b2b1ca4
license    : MIT
component  : desktop.library
summary    : A modular Wayland compositor library
description: |
    Pluggable, composable, unopinionated modules for building a Wayland compositor
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(libavcodec)
    - pkgconfig(libdrm)
    - pkgconfig(libinput)
    - pkgconfig(libpng)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
    - pkgconfig(xcb-icccm)
setup      : |
    %meson_configure -Dx11-backend=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
