name       : btop
version    : 1.2.7
release    : 4
source     :
    - https://github.com/aristocratos/btop/archive/refs/tags/v1.2.7.tar.gz : 60075824ca4e14c1ca920b76ffb101fc2340c5342f3ba600b5c280389b69bbbf
license    : Apache-2.0
component  : system.utils
summary    : Terminal resource monitor that shows usage and stats for processor, memory, disks, network and processes
description: |
    Terminal resource monitor that shows usage and stats for processor, memory, disks, network and processes
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
