name       : et
version    : 6.1.8
release    : 1
source     :
    - https://github.com/MisterTea/EternalTerminal/archive/refs/tags/et-v6.1.8.tar.gz : c82c62722d5e4db5b4596bcaafd4a4cf8c236968cb3782f791f5c38a62b10fb9
license    : apache-2.0
component  : network.util
summary    : Eternal Terminal (ET) is a remote shell that automatically reconnects without interrupting the session
description: |
    Eternal Terminal (ET) is a remote shell that automatically reconnects without interrupting the session
builddeps :
    - pkgconfig(libcurl)
    - pkgconfig(libsodium)
    - pkgconfig(protobuf)
setup      : |
    %cmake_ninja -DDISABLE_VCPKG=TRUE
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
