name       : eternal-terminal
version    : 6.2.9
release    : 2
source     :
    - https://github.com/MisterTea/EternalTerminal/archive/refs/tags/et-v6.2.9.tar.gz : 13bfb2722b011b5f0a28fa619508deca96deec9eee5e42b922add0c166d8185a
license    : Apache-2.0
homepage   : https://mistertea.github.io/EternalTerminal
component  : network.clients
summary    : Re-Connectable secure remote shell
description: |
    Eternal Terminal is a remote shell that automatically reconnects without interrupting the session
builddeps  :
    - libboost-devel
    - pkgconfig(gflags)
    - pkgconfig(libcurl)
    - pkgconfig(libsodium)
    - pkgconfig(protobuf)
setup      : |
    %cmake_ninja -DDISABLE_VCPKG=TRUE
build      : |
    %ninja_build
install    : |-
    %ninja_install
    install -Dm00644 $workdir/systemctl/et.service $installdir/usr/lib/systemd/system/et.service
    install -Dm00644 $workdir/etc/et.cfg $installdir/etc/et/et.cfg
