name       : eternal-terminal
version    : 6.2.1
release    : 1
source     :
    - https://github.com/MisterTea/EternalTerminal/archive/refs/tags/et-v6.2.1.tar.gz : fdf68a51cb8b62b3dbbacd1d2aeba5d5491e5142e65c97713c2f1ce61d4fdbed
license    : Apache-2.0
homepage   : https://mistertea.github.io/EternalTerminal
component  : network.clients
summary    :  Re-Connectable secure remote shell
description: |
    Eternal Terminal is a remote shell that automatically reconnects without interrupting the session
builddeps  :
    - libboost-devel
    - pkgconfig(gflags)
    - pkgconfig(libcurl)
    - pkgconfig(libsodium)
    - pkgconfig(protobuf)
setup      : |
    %cmake_ninja -DDISABLE_VCPKG=TRUE
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $workdir/systemctl/et.service $installdir/usr/lib/systemd/system/et.service
    install -Dm00644 $workdir/etc/et.cfg $installdir/etc/et/et.cfg