name       : sile
version    : 0.14.3
release    : 1
source     :
    - https://github.com/sile-typesetter/sile/archive/refs/tags/v0.14.3.tar.gz : 8e0b2d566b714e4ff1e753f4b27d293aaa8955d16130486920f88cc6d92818c4
    - https://github.com/sile-typesetter/libtexpdf/archive/736a5e7530c13582ea704a061a358d0caa774916.zip : 6ad577986219880640b1579dcaa1ca9a43cf2197e1e8956ac9761cac1277b536
license    : MIT
homepage   : https://sile-typesetter.org/
component  : programming
summary    : Simon’s Improved Layout Engine
description: |
    Simon’s Improved Layout Engine
builddeps  :
    - pkgconfig(harfbuzz)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - lua-devel
    - luarocks

setup      : |
    unzip "${sources}/736a5e7530c13582ea704a061a358d0caa774916.zip"
    cp -r libtexpdf-736a5e7530c13582ea704a061a358d0caa774916 libtexpdf
    %cmake_ninja 
build      : |
    %make --with-system-luarocks
install    : |
    %make-install
