name       : tmatrix
version    : 1.3
release    : 1
source     :
    - https://github.com/M4444/TMatrix/archive/v1.3.tar.gz : 4290b755ffbfe115ec8c24b56f45f6c8cf8672ffa0dfb0d0720d7e27e03ab9f2
license    : GPL-2.0-only
component  : desktop
summary    : Terminal based replica of the digital rain from The Matrix
description: |
    Terminal based replica of the digital rain from The Matrix
builddeps  :
    - pkgconfig(ncursesw)
build      : |
    mkdir -p build && cd build
    cmake ..
    %make

install    : |
    cd build
    %make_install
