name       : lapace 
version    : 0.2.0
release    : 1
source     :
    - https://github.com/lapce/lapce/archive/refs/tags/v0.2.0.tar.gz : 163102244c6586530bc0f0736219d38a44797b2a6d97ad37d5f6553ffc8f1a04
license    : Apache-2.0
homepage   : https://lapce.dev/
component  : editor
summary    : Lightning-fast and Powerful Code Editor written in Rust 
description: |
    Lightning-fast and Powerful Code Editor written in Rust
networking: yes
builddeps  :
    - cargo
    #- pkgconfig(cairo 
    - perl-cairo-gobject
    - pkgconfig(atk)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(pango)
    
build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/lapace $installdir/usr/bin/lapace
