name       : bit
version    : 1.1.2
release    : 5
source     :
    - https://github.com/chriswalz/bit/archive/refs/tags/v1.1.2.tar.gz : 563ae6b0fa279cb8ea8f66b4b455c7cb74a9e65a0edbe694505b2c8fc719b2ff
license    : Apache-2.0
component  : programming.tools
homepage   : https://github.com/chriswalz/bit
summary    : bit is an experimental modernized git CLI built on top of git that provides happy defaults and other niceties
description: |
    bit is an experimental modernized git CLI built on top of git that provides happy defaults and other niceties
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o bit
install    : |
    install -Dm00755 $workdir/bit $installdir/usr/bin/bit
