name       : python-grpcio-tools
version    : 1.43.0
# This version should match python-grcpio
release    : 2
source     :
    - https://files.pythonhosted.org/packages/55/7a/b6d5a5d69d6ab0df70a7ceed16f0e9a6c0bdc09376c92fa5638d08803fa4/grpcio-tools-1.43.0.tar.gz : f42f1d713096808b1b0472dd2a3749b712d13f0092dab9442d9c096446e860b2
license    : Apache-2.0
component  : programming.python
summary    : Python protobuf generator for GRPC
description: |
    Python protobuf generator for GRPC
builddeps  :
    - pkgconfig(python3)
    - python-grpcio
    - python-protobuf
build      : |
    %python3_setup
install    : |
    %python3_install
