name       : lapce-binary
version    : 0.3.0
release    : 5
source     :
    - https://github.com/lapce/lapce/releases/download/v0.3.0/Lapce-linux.tar.gz : 42544244dd897f94f921046ad3af64da1a6a1c6eabc5739fbe409ff9147abd17
license    : Apache-2.0
homepage   : https://lapce.dev/
component  : editor
summary    : Lightning-fast and Powerful Code Editor written in Rust
description: |
    Lightning-fast and Powerful Code Editor written in Rust
install    : |
    install -Dm00755 $workdir/lapce $installdir/usr/bin/lapce
    install -Dm00755 $pkgfiles/lapce.desktop $installdir/usr/share/applications/dev.lapce.lapce.desktop
    install -Dm0644 $pkgfiles/logo.png  $installdir/usr/share/pixmaps/dev.lapce.lapce.png
