name       : vagrant
version    : 2.2.19
release    : 1
source     :
    - https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_linux_amd64.zip : a1df4c793902e2b9647a0fd42a23d2363c6900f54b70674b736898f9e48c1200
license    : MIT
homepage   : https://www.vagrantup.com/
component  : programming
summary    : Vagrant is a tool for building and distributing development environments.
description: |
    Vagrant is a tool for building and distributing development environments.
install    : |
    install -Dm00755 $workdir/vagrant $installdir/usr/bin/vagrant
