name       : dillo
version    : 3.2.0
release    : 3
source     :
    - https://codeberg.org/dillo/dillo/archive/v3.2.0.tar.gz : 38bfacab92277967b72325452d0d6b1f783ea5b110fa24fb3541c21a8b26ffdd
homepage   : https://dillo-browser.github.io/
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : Multi-platform graphical web browser
description: |
    Multi-platform graphical web browser, known for its speed and small footprint, that is developed with a focus on personal security and privacy
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xft)
    - pkgconfig(xrender)
    - fltk-devel
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
