name       : dillo
version    : 3.1.1
release    : 2
source     :
    - https://github.com/dillo-browser/dillo/archive/refs/tags/v3.1.1.tar.gz : dffc0bca7620117c42f045b972cffafffbe113927a698cdbd8970857e4b3d3ed
homepage   : https://dillo-browser.github.io/
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : Multi-platform graphical web browser
description: |
    Multi-platform graphical web browser, known for its speed and small footprint, that is developed with a focus on personal security and privacy
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xft)
    - pkgconfig(xrender)
    - fltk-devel
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
