name       : hugo
version    : 0.100.1
release    : 134
source     :
    - https://github.com/gohugoio/hugo/archive/refs/tags/v0.100.1.tar.gz : 030fa0a75005dcdfd0b1ef3686859977d234d89d6d73839e7ac8695262aabff5
license    : Apache-2.0
homepage   : https://gohugo.io
component  : programming
networking : yes
extract    : no
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - git
    - mage
setup      : |
    mkdir -p src/github.com/gohugoio/hugo
    tar xf $sources/v${version}.tar.gz -C src/github.com/gohugoio/hugo --strip-components 1
build      : |
    cd ..
    export GO111MODULE=on
    export HUGO_BUILD_TAGS=extended
    export GOPATH=`pwd`
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    cd src/github.com/gohugoio/hugo
    mage hugo
install    : |
    cd src/github.com/gohugoio/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
