name       : numbat
version    : 1.11.0
release    : 3
source     :
    - https://github.com/sharkdp/numbat/archive/refs/tags/v1.11.0.tar.gz : 9543f449e758b2db6d1299b4eee88dbeac1ba57a427580c7f45d3ee613b089a0
homepage   : https://numbat.dev/
license    :
    - Apache-2.0
    - MIT
component  : system.util
summary    : A statically typed programming language for scientific computations with first class support for physical dimensions and units
description: |
    A statically typed programming language for scientific computations with first class support for physical dimensions and units
networking : yes
builddeps  :
    - cargo
setup      : |
    cargo fetch --locked
build      : |
    cargo build --frozen --release
install    : |
    install -Dm00755 target/release/numbat $installdir/usr/bin/numbat
    mkdir -p $installdir/usr/share/numbat
    cp -r numbat/modules $installdir/usr/share/numbat
