name       : chrono-date
version    : 3.0.0
release    : 1
source     : 
    - https://github.com/HowardHinnant/date/archive/v3.0.0.tar.gz : 87bba2eaf0ebc7ec539e5e62fc317cb80671a337c1fb1b84cb9e4d42c6dbebe3
license    : MIT
component  : programming.devel
summary    : A date and time library based on the C++11/14/17 <chrono> header
description: |
    A date and time library based on the C++11/14/17 <chrono> header
builddeps  :
    - pkgconfig(libcurl)
setup      : |
    %cmake -DBUILD_TZ_LIB=ON
build      : |
    cmake --build .
install    : |
    %make_install