name       : wormhole-gui
version    : 2.2.0
release    : 1
source     :
    - https://github.com/Jacalz/wormhole-gui/archive/refs/tags/v2.2.0.tar.gz : 3f81b045dd8804f610395f028a91ea4eab0fb743ae40c4a82421792424a9c7c1
license    : GPL-3.0-or-later
homepage   : https://github.com/Jacalz/wormhole-gui
component  : network.client
summary    : Wormhole-gui is a cross-platform graphical interface for magic-wormhole
description: |
    Wormhole-gui is a cross-platform graphical interface for magic-wormhole that lets you easily share files, folders and text between devices. It uses the Go implementation of magic-wormhole, called wormhole-william, and compiles statically into a single binary. Wormhole-gui is compatible with the cli applications from both wormhole-william and magic-wormhole.
networking : yes
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
    - golang
build      : |
    %make
install    : |
    %make_install
