name       : jekyll
version    : 4.0.0
release    : 1
source     :
    - https://rubygems.org/downloads/jekyll-4.0.0.gem : 4a1dc48895d525bfb98cd562bf03ab6dd2727b5795360877c90e12670b9fec3a
license    : MIT
component  : programming.ruby
summary    : JJekyll is a static site generator written in Ruby.
description: |
    Jekyll is a static site generator written in Ruby.
builddeps  :
    - pkgconfig(ruby-2.6)
install    : |
    %gem_install
    rm -rf $installdir%libdir%/ruby/gems/2.6.0/doc
    rm -rf $installdir%libdir%/ruby/gems/2.6.0/build_info
    rm -rf $installdir%libdir%/ruby/gems/2.6.0/extensions
    rm $installdir%libdir%/ruby/gems/2.6.0/gems/jekyll-%version%/LICENSE
    rm $installdir%libdir%/ruby/gems/2.6.0/gems/jekyll-%version%/README.markdown
