name       : get-iplayer 
version    : 3.31
release    : 1
source     :
    - https://github.com/get-iplayer/get_iplayer/archive/refs/tags/v3.31.tar.gz : 21bc00887365034f76e56b829eeba8b6d510f83424ebf1840ff9ca76713f58d5
license    : GPL-3.0-or-later
component  : network.download
summary    : BBC iPlayer/BBC Sounds Indexing Tool and PVR
description: |
    BBC iPlayer/BBC Sounds Indexing Tool and PVR
rundeps    :
    - ffmpeg
    - libwww-perl
    - perl-xml-libxml
    - perl-lwp-protocol-https
    - perl-mojolicious
install    : |
    install -Dm00755 {get_iplayer,get_iplayer.cgi} -t $installdir/usr/bin
    install -Dm00644 get_iplayer.1 -t $installdir/usr/share/man/man1
