name       : chezmoi
version    : 2.62.5
release    : 23
source     :
    - https://github.com/twpayne/chezmoi/archive/refs/tags/v2.62.5.tar.gz : 7c61756eb0de7a4f319e9ac86788fcc04b8863518477c1541454974c08742755
license    : MIT
homepage   : https://www.chezmoi.io
component  : programming.tools
summary    : chezmoi helps you manage your personal configuration files across multiple machines.
description: |
    chezmoi helps you manage your personal configuration files across multiple machines.
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
