name       : chezmoi
version    : 2.58.0
release    : 17
source     :
    - https://github.com/twpayne/chezmoi/archive/refs/tags/v2.58.0.tar.gz : 50ac56d7e0624c5b1df2f451fbdec5c46e0e381476e8f2212669840de0d42984
license    : MIT
homepage   : https://www.chezmoi.io
component  : programming.tools
summary    : chezmoi helps you manage your personal configuration files across multiple machines.
description: |
    chezmoi helps you manage your personal configuration files across multiple machines.
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
