name       : chezmoi
version    : 2.59.1
release    : 18
source     :
    - https://github.com/twpayne/chezmoi/archive/refs/tags/v2.59.1.tar.gz : 577bce7c9038ca17cda2c61c1ff3df90c4b366b68629e3056e274cf4b319be30
license    : MIT
homepage   : https://www.chezmoi.io
component  : programming.tools
summary    : chezmoi helps you manage your personal configuration files across multiple machines.
description: |
    chezmoi helps you manage your personal configuration files across multiple machines.
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
