name       : chezmoi
version    : 2.60.1
release    : 19
source     :
    - https://github.com/twpayne/chezmoi/archive/refs/tags/v2.60.1.tar.gz : de4cfaf2aee8d2eaa83a4945253386991a08d3d2e9262846b18df3bfa0252419
license    : MIT
homepage   : https://www.chezmoi.io
component  : programming.tools
summary    : chezmoi helps you manage your personal configuration files across multiple machines.
description: |
    chezmoi helps you manage your personal configuration files across multiple machines.
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
