name       : waybar
version    : 0.9.4
release    : 1
source     :
    - https://github.com/Alexays/Waybar/archive/0.9.4.tar.gz : d49c09ee253ca9cc9688d1b4d8602adc9bdae613b02e2fa1a2e7277ddc9e82e8
license    : MIT
component  : desktop
summary    : Highly customizable Wayland bar for Sway and Wlroots based compositors
description: |
    Highly customizable Wayland bar for Sway and Wlroots based compositors
networking : yes
#clang      : yes
builddeps  :
    - git
    - pkgconfig(dbusmenu-gtk3-0.4)
    - pkgconfig(fmt)
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(gtk-layer-shell-0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libmpdclient)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(scdoc)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(spdlog)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - sndio-devel
    - pkgconfig(libinput)
    - pkgconfig(libudev)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gio-unix-2.0)
#    - llvm-clang

rundeps    :
    - font-awesome-ttf


setup      : |
    %patch -p1 < $pkgfiles/0001-network-module-fix.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
# pulled by gtk-layer-shell
#    - pkgconfig(gobject-introspection-1.0)
#    - pkgconfig(gtk+-wayland-3.0)
# used by fedora build
#    - pkgconfig(libinput)
#    - pkgconfig(libudev)
#    - pkgconfig(gio-unix-2.0)
#    - pkgconfig(gio-unix-2.0)
