name       : croc
version    : 10.1.1
release    : 15
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.1.1.tar.gz : 7351abed3bb509e6c13f1a9d8c38662dcafc29f8b1e123127e8ee75e7eb0719b
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
