name       : croc
version    : 9.2.0
release    : 1
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v9.2.0.tar.gz : e8f72be7f3c26a1c4ed00c3ebb222d2959cd6c7f7f74a097a556b56e6a24ba96
license    : MIT
component  : networking.tools
homepage   : https://github.com/schollz/croc
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
