name       : croc
version    : 9.4.2
release    : 3
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v9.4.2.tar.gz : 73d3abb058af18329ffdea4bb77d484b5f8ede9c11010d44781f3e891aa675e0
license    : MIT
component  : networking.tools
homepage   : https://github.com/schollz/croc
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
