name       : croc
version    : 9.6.16
release    : 10
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v9.6.16.tar.gz : d535362d0900e841090e48cd1d026bca66f428786adc627a95fe61f1e0ea8c00
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
