name       : croc
version    : 10.3.1
release    : 20
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.3.1.tar.gz : 098f9f7295843b09378dd49877ef189aaafac8e6255a346a5f1f9ce310538312
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
