name       : croc
version    : 9.6.5
release    : 7
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v9.6.5.tar.gz : 2d3ba7bae3c49e3870e2f8523c6be00e92fe6e46828269a8cea34d4034102cad
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
