name       : croc
version    : 10.2.2
release    : 18
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.2.2.tar.gz : 1d892bbf3f8dacd0f528f683ab6c3678483374b17076187da7d1af805326fa68
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
