name       : croc
version    : 10.0.12
release    : 12
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.0.12.tar.gz : 849670f3525a316c44787119e1f86365f7c81d66d8b52877ac5b314e226a1eb7
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
