name       : croc
version    : 10.4.0
release    : 21
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.4.0.tar.gz : c4f6266c47c113ea8601d08789a84521854e46d5c14b77a4cdc1e8c774f8d31c
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
