name       : croc
version    : 10.0.5
release    : 11
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.0.5.tar.gz : a5d1dc841d01a15e7ccec4280aa0905c69d4076236e1dd53513cde90097688a7
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
