name       : croc
version    : 10.1.3
release    : 16
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.1.3.tar.gz : 3bce38e7d74714bb7ca00791ee9771935a4d2c5dac8a8831b6713f49c1ec4207
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
