name       : croc
version    : 10.0.13
release    : 13
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.0.13.tar.gz : 69a7e60811b97d3f6e2ceac4d24fc52596ec8982039811fb5894ef78f2dedc77
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
