name       : croc
version    : 10.1.0
release    : 14
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.1.0.tar.gz : 0968f28c0d46ff181173ae1613aea5c55757384e3c1358917f78bf0ce595d151
license    : MIT
component  : networking.tools
homepage   : https://schollz.com/tinker/croc6/
summary    : croc is a tool that allows any two computers to simply and securely transfer files and folders
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o croc
install    : |
    install -Dm00755 $workdir/croc $installdir/usr/bin/croc
