# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : whosthere
version    : 0.8.3
release    : 5
source     :
    - https://github.com/ramonvermeulen/whosthere/archive/refs/tags/v0.8.3.tar.gz : e6f4203fc62464e160349f342ff34103f89c6cb516d18ce6c7ba2bf6e398a2b5
homepage   : https://github.com/ramonvermeulen/whosthere
license    : Apache-2.0
component  : network.util
summary    : Local Area Network discovery tool with a modern Terminal User Interface
description: |
    Local Area Network discovery tool with a modern Terminal User Interface (TUI) written in Go. Discover, explore, and understand your LAN in an intuitive way.
networking : true
builddeps  :
    - pkgconfig(x11)
    - golang
build      : |
    go build -o whosthere
install    : |
    install -Dm00755 whosthere $installdir/usr/bin/whosthere
    %install_license LICENSE
