# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : whosthere
version    : 0.7.0
release    : 4
source     :
    - https://github.com/ramonvermeulen/whosthere/archive/refs/tags/v0.7.0.tar.gz : 73a7dfc2b31c74ae1fc0cf56d68fbcd6dfe47be53adfdafa5b00be17da7477d2
homepage   : https://github.com/ramonvermeulen/whosthere
license    : Apache-2.0
component  : network.util
summary    : Local Area Network discovery tool with a modern Terminal User Interface
description: |
    Local Area Network discovery tool with a modern Terminal User Interface (TUI) written in Go. Discover, explore, and understand your LAN in an intuitive way.
networking : true
builddeps  :
    - pkgconfig(x11)
    - golang
build      : |
    go build -o whosthere
install    : |
    install -Dm00755 whosthere $installdir/usr/bin/whosthere
    %install_license LICENSE
