name       : lazygit
version    : 0.20.6
release    : 1
source     :
    - https://github.com/jesseduffield/lazygit/archive/v0.20.6.tar.gz : 9497c5a9e8bc26673d137c3daaf5938ac0b5326a4b08507e6ec3a035b6ef2be3
license    : MIT
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
    - go-md2man
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

    # Make a man page
    go-md2man -in README.md -out lazygit.1
install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
    install -Dm00644 $workdir/lazygit.1 $installdir/usr/man/man1/lazygit.1
