name       : halloy
version    : 2024.12
release    : 1
source     :
    - https://github.com/squidowl/halloy/archive/refs/tags/2024.12.tar.gz : df773c2e7ad6bf335fe2cdfd721f8873550cfb5554a9c1734bae76cee1282871
homepage   : https://halloy.squidowl.org/
license    : GPL-3.0-or-later
component  : network.im
summary    : IRC application written in Rust
description: |
      Halloy is an open-source IRC client written in Rust, with the Iced GUI library. It aims to provide a simple and fast client for Mac, Windows, and Linux platforms.
networking: yes
builddeps  :
    - pkgconfig(alsa)
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
    install -Dm00644 assets/linux/org.squidowl.halloy.desktop -t $installdir/usr/share/applications
    install -Dm00644 assets/linux/org.squidowl.halloy.appdata.xml -t $installdir/usr/share/metainfo
    cp -r assets/linux/icons $installdir/usr/share
