name       : wl-clipboard
version    : 2.1.0
release    : 1
source     :
    - https://github.com/bugaevc/wl-clipboard/archive/refs/tags/v2.1.0.tar.gz : 72dab9a7d3835c76d6ff2089f15ffec9e064a321e5f3cbbe961a8fa81aff5573
license    : GPL-3.0-or-later
component  : desktop
summary    : Command-line copy/paste utilities for Wayland 
description: |
    This project implements two command-line Wayland clipboard utilities, wl-copy and wl-paste, that let you easily copy data between the clipboard and Unix pipes, sockets, files and so on.
builddeps  :
    - pkgconfig(wayland-client)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
