name       : lapce
version    : 0.2.7
release    : 3
source     :
    - https://github.com/lapce/lapce/archive/refs/tags/v0.2.7.tar.gz : c4e0668bf98e83a8c451fe69173c51d8345511a1bd580c412750f3b940531c27
license    : Apache-2.0
homepage   : https://lapce.dev/
component  : editor
summary    : Lightning-fast and Powerful Code Editor written in Rust
description: |
    Lightning-fast and Powerful Code Editor written in Rust
networking : yes
builddeps  :
    - cargo
    - perl-cairo-gobject
    - pkgconfig(atk)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(pango)

build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/lapce $installdir/usr/bin/lapce

# This is slow to build with all the fetching involved, use the binary
