name       : lapce
version    : 0.3.1
release    : 4
source     :
    - https://github.com/lapce/lapce/archive/refs/tags/v0.3.1.tar.gz : 82407a0b0ae8a5660ff2192ca336c9b0e361424f0fd509e0a0a73ad55071f13d
homepage   : https://lapce.dev/
license    : Apache-2.0
component  : editor
summary    : Lightning-fast and Powerful Code Editor written in Rust
description: |
    Lapce (IPA: /læps/) is written in pure Rust with a UI in Floem. It is designed with Rope Science from the Xi-Editor which makes for lightning-fast computation, and leverages Wgpu for rendering. More information about the features of Lapce can be found on the main website and user documentation can be found on GitBook.
networking : yes
clang      : yes
builddeps  :
    - cargo
setup      : |
    cargo fetch --locked --target "x86_64-unknown-linux-gnu"
build      : |
    cargo build --frozen --profile release-lto --all-features
install    : |
    install -Dm00755 -t $installdir/usr/bin/ target/release-lto/lapce{,-proxy}
    install -Dm00644 -t $installdir/usr/share/applications/ extra/linux/dev.lapce.lapce.desktop
    install -Dm00644 -t $installdir/usr/share/metainfo/ extra/linux/dev.lapce.lapce.metainfo.xml
    install -Dm00644 extra/images/logo_app.svg $installdir/usr/share/icons/hicolor/scalable/apps/dev.lapce.lapce.svg
check      : |
    cargo test --release --locked