name       : zerotier-one
version    : 1.16.2
release    : 23
source     :
    - https://github.com/zerotier/ZeroTierOne/archive/refs/tags/1.16.2.tar.gz : 2c607f573c6e38815433af289d364a689a203b18b51125f06c4472014d0657f0
license    : Business Source License 1.1
component  : network.clients
summary    : Zerotier is an open source, cross-platform virtual LAN
description: |
    Zerotier is an open source, cross-platform virtual LAN
clang      : yes
build      : |
    %make ZT_SSO_SUPPORTED=0
    make selftest ZT_SSO_SUPPORTED=0
    ./zerotier-selftest
install    : |
    %make_install

    # Install and enable systemd service
    install -Dm00644 -t $installdir/usr/lib/systemd/system/ $workdir/debian/zerotier-one.service
    install -Dm00644 -t ${installdir}/%libdir%/systemd/system-preset/ ${pkgfiles}/20-zerotier-one.preset

# SSO reguires cargo, rust, networking libssl?. Don't care about SSO.
