name       : zerotier-one
version    : 1.12.1
release    : 16
source     :
    - https://github.com/zerotier/ZeroTierOne/archive/refs/tags/1.12.1.tar.gz : c6758a04f161bba1c0ef11fce991029a645ede381ae3862a25a2f5145aaffca8
license    : Business Source License 1.1
component  : network.clients
summary    : Zerotier is an open source, cross-platform virtual LAN
description: |
    Zerotier is an open source, cross-platform virtual LAN
clang      : yes
build      : |
    %make ZT_SSO_SUPPORTED=0
    make selftest ZT_SSO_SUPPORTED=0
    ./zerotier-selftest
install    : |
    %make_install
    install -D -m 00644 $workdir/debian/zerotier-one.service $installdir/usr/lib/systemd/system/zerotier-one.service

# SSO reguires cargo, rust, networking libssl?. Don't care about SSO.
