name       : zerotier-one
version    : 1.12.2
release    : 18
source     :
    - https://github.com/zerotier/ZeroTierOne/archive/refs/tags/1.12.2.tar.gz : 7c6512cfc208374ea9dc9931110e35f71800c34890e0f35991ea485aae66e31c
license    : Business Source License 1.1
component  : network.clients
summary    : Zerotier is an open source, cross-platform virtual LAN
description: |
    Zerotier is an open source, cross-platform virtual LAN
clang      : yes
build      : |
    %make ZT_SSO_SUPPORTED=0
    make selftest ZT_SSO_SUPPORTED=0
    ./zerotier-selftest
install    : |
    %make_install
    install -D -m 00644 $workdir/debian/zerotier-one.service $installdir/usr/lib/systemd/system/zerotier-one.service

# SSO reguires cargo, rust, networking libssl?. Don't care about SSO.
