name       : zerotier-one
version    : 1.6.3
release    : 4
source     :
    - https://github.com/zerotier/ZeroTierOne/archive/1.6.3.tar.gz : 437d51a396e65f45822b0e5ee3761e3dfaf3507d9cc8f9b01e09c5541395d7b2
license    : Business Source License 1.1
component  : network.clients
summary    : Zerotier is an open source, cross-platform virtual LAN
description: |
    Zerotier is an open source, cross-platform virtual LAN
build      : |
    %make
    make selftest
    ./zerotier-selftest
install    : |-
    %make_install
    install -D -m 00644 $workdir/debian/zerotier-one.service $installdir/usr/lib/systemd/system/zerotier-one.service
