name       : diff-so-fancy
version    : 1.4.10
release    : 2
source     :
    - https://github.com/so-fancy/diff-so-fancy/archive/refs/tags/v1.4.10.tar.gz : 9df1e7b5c47f1f70ea5d23b18a5994c431548029448465256a93b3b7cfeb0b4a
homepage   : https://github.com/so-fancy/diff-so-fancy
license    : MIT
component  : programming.tools
summary    : Good-lookin' diffs. Actually… nah… The best-lookin' diffs
description: |
    Good-lookin' diffs. Actually… nah… The best-lookin' diffs
rundeps    :
    - perl
setup      : |
    # Thanks AUR
    sed -i 's|^use lib .*$|use lib "/usr/share/diff-so-fancy";|' "diff-so-fancy"
install    : |
    install -Dm00755 $workdir/diff-so-fancy $installdir/usr/bin/diff-so-fancy
    install -Dm00755 $workdir/lib/DiffHighlight.pm $installdir/usr/share/diff-so-fancy/DiffHighlight.pm
