name       : diff-so-fancy
version    : 1.4.12
release    : 4
source     :
    - https://github.com/so-fancy/diff-so-fancy/archive/refs/tags/v1.4.12.tar.gz : 438cccf785cc8ac1575a81ca606afdbb8a4de8f860136d9f26a1807b00903f5d
homepage   : https://github.com/so-fancy/diff-so-fancy
license    : MIT
component  : programming.tools
summary    : Good-lookin' diffs. Actually… nah… The best-lookin' diffs
description: |
    Good-lookin' diffs. Actually… nah… The best-lookin' diffs
rundeps    :
    - perl
setup      : |
    # Thanks AUR
    sed -i 's|^use lib .*$|use lib "/usr/share/diff-so-fancy";|' "diff-so-fancy"
install    : |
    install -Dm00755 $workdir/diff-so-fancy $installdir/usr/bin/diff-so-fancy
    install -Dm00755 $workdir/lib/DiffHighlight.pm $installdir/usr/share/diff-so-fancy/DiffHighlight.pm
