name       : diff-so-fancy
version    : 1.4.6
release    : 2
source     :
    - https://github.com/so-fancy/diff-so-fancy/archive/refs/tags/v1.4.6.tar.gz : 50db311c9444b080361d3bfc0cf0180715fae4c682316673f707179ee9718f93
homepage   : https://github.com/so-fancy/diff-so-fancy
license    : MIT
component  : programming.tools
summary    : Good-lookin' diffs. Actually… nah… The best-lookin' diffs
description: |
    Good-lookin' diffs. Actually… nah… The best-lookin' diffs
rundeps    :
    - perl
setup      : |
    # Thanks AUR
    sed -i 's|^use lib .*$|use lib "/usr/share/diff-so-fancy";|' "diff-so-fancy"
install    : |
    install -Dm00755 $workdir/diff-so-fancy $installdir/usr/bin/diff-so-fancy
    install -Dm00755 $workdir/lib/DiffHighlight.pm $installdir/usr/share/diff-so-fancy/DiffHighlight.pm
