name       : activate-linux
version    : 0.0.2
release    : 2
source     :
    - https://github.com/MrGlockenspiel/activate-linux/archive/refs/tags/v0.0.2.tar.gz : d6235b9d13bd896a130a83cc6d882da677fb19edb5a76735453b866aa0e7690d
license    : GPL-3.0-or-later
component  : desktop
summary    : The "Activate Windows" watermark ported to Linux
clang      : yes
description: |
    The "Activate Windows" watermark ported to Linux 
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
build      : |
    %make 
install    : |
    %make_install PREFIX=/usr/
