name       : swaybg
version    : 1.0
release    : 1
source     :
    - https://github.com/swaywm/swaybg/archive/1.0.tar.gz : a23f1cde07138b865630172eff83db916d2f0989b75fb318def85dcfc3120fbd
license    : MIT
component  : desktop
summary    : Wallpaper utility for Wayland compositors
description: |
    Wallpaper utility for Wayland compositors
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
