name       : opensnitch
version    : 1.3.0
release    : 1
source     :
    - https://github.com/evilsocket/opensnitch/archive/v1.3.0.tar.gz : 37d17d034c775831a111e520b799d672512d62173a4cffb129fd112c7e7aecff
license    : GPL-3.0-or-later
component  : networking.util
summary    : OpenSnitch is a GNU/Linux application firewall.
description: |
    OpenSnitch is a GNU/Linux application firewall.
builddeps  :
    - python-grpcio
    - python-grpcio-tools
    - python-protobuf
    - python-slugify

build      : |
    %make
install    : |
    %make_install

# Notes
# - pythhon grpcio-tools is local, slow af to build
