name       : aerc
version    : 0.16.0
release    : 6
source     :
    - https://git.sr.ht/~rjarry/aerc/archive/0.16.0.tar.gz : b81b4f27272df2e370da377438a500c0695d29b8a4c86ff5849d6ddf3433f4db
license    : MIT
homepage   : https://aerc-mail.org/
component  : network.mail
summary    : aerc is an email client for your terminal.
description: |
    aerc is an email client for your terminal.
networking : yes
builddeps  :
    - pkgconfig(scdoc)
    - golang
    - notmuch-devel
rundeps    :
    - libvterm
    - python-colorama
    - w3m
build      : |
    %make PREFIX=/usr GOFLAGS=-tags=notmuch
install    : |
    %make_install PREFIX=/usr
