name       : aerc
version    : 0.1.1
release    : 1
source     :
    - https://git.sr.ht/~sircmpwn/aerc/archive/0.1.1.tar.gz : eb9f6cf6f77b1eef25d04d7c7cd05fdaebd3d41cd47fa95230b222acac94fc66
license    : MIT
component  : network.mail
summary    : aerc is an email client for your terminal.
description: |
    aerc is an email client for your terminal.
    # networking : yes
builddeps  :
    - golang
    - pkgconfig(scdoc)
    - git
rundeps    :
    - libvterm
    - w3m
    - python3-colorama
environment: |
    export GOPATH=$workdir \
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
