name       : aerc
version    : '0.30'
release    : 4
source     :
    - https://git.sr.ht/~sircmpwn/aerc/archive/0.3.0.tar.gz : 44d5ab0d5f1195166b351ec59680cc8f4c0eb45da4d44263b138be0a91a512a1
license    : MIT
component  : network.mail
summary    : aerc is an email client for your terminal.
description: |
    aerc is an email client for your terminal.
builddeps  :
    - pkgconfig(scdoc)
    - golang
rundeps    :
    - libvterm
    - w3m
    - python3-colorama
environment: |
    export GOPATH=`pwd`
networking : yes
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
