name       : wmenu
version    : 0.1.6
release    : 1
source     :
    - https://git.sr.ht/~adnano/wmenu/archive/0.1.6.tar.gz : 0684739e6339ffad6562338a4bf67e29bf18688d1a9b0ddf31b693a64d29efac
homepage   : https://git.sr.ht/~adnano/wmenu
license    : MIT
component  : desktop
summary    : Wayland-native dmenu replacement which maintains the look and feel of dmenu
description: |
    wmenu is an efficient dynamic menu for Sway and wlroots based Wayland compositors. It provides a Wayland-native dmenu replacement which maintains the look and feel of dmenu
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(pango)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
    - scdoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
