name       : polyml
version    : 5.8.1
release    : 1
source     :
    - https://github.com/polyml/polyml/archive/v5.8.1.tar.gz : fa0507b44470b4e07a061ef6a8896efe42710d8436e15721d743572ad2f7753b
license    : LGPL-2.1-or-later
component  : programming
summary    : Poly/ML is a Standard ML implementation originally written in an experimental language called Poly.
description: |
    Poly/ML is a Standard ML implementation originally written in an experimental language called Poly.
setup      : |
    %configure --enable-shared --disable-static --with-system-libffi 
build      : |
    %make
install    : |
    %make_install
check      : |
    make check
