name       : lazydocker
version    : 0.24.1
release    : 5
source     :
    - https://github.com/jesseduffield/lazydocker/archive/refs/tags/v0.24.1.tar.gz : f54197d333a28e658d2eb4d9b22461ae73721ec9e4106ba23ed177fc530c21f4
homepage   : https://github.com/jesseduffield/lazydocker
license    : MIT
component  : programming.tools
summary    : A simple terminal UI for both docker and docker-compose
description: |
    A simple terminal UI for both docker and docker-compose, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazydocker

install    : |
    install -Dm00755 $workdir/lazydocker $installdir/usr/bin/lazydocker
