name       : python-ruamel-yaml-clib
version    : 0.2.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/92/28/612085de3fae9f82d62d80255d9f4cf05b1b341db1e180adcf28c1bf748d/ruamel.yaml.clib-0.2.0.tar.gz : b66832ea8077d9b3f6e311c4a53d06273db5dc2db6e8a908550f3c14d67e718c
homepage   : https://pypi.org/project/ruamel.yaml.clib/
license    : MIT
component  : programming.python
summary    : C version of reader, parser and emitter for ruamel.yaml derived from libyaml
description: |
    This package was split of from ruamel.yaml, so that ruamel.yaml can be build as a universal wheel. Apart from the C code seldom changing, and taking a long time to compile for all platforms, this allows installation of the .so on Linux systems under /usr/lib64/pythonX.Y (without a .pth file or a ruamel directory) and the Python code for ruamel.yaml under /usr/lib/pythonX.Y.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install --single-version-externally-managed
