name       : fmt
version    : 7.1.0
release    : 5
source     :
    - https://github.com/fmtlib/fmt/archive/7.1.0.tar.gz : a53bce7e3b7ee8c7374723262a43356afff176b1684b86061748409e6f8b56c5
license    : BSD-2-Clause
component  : programming.library
summary    : Small, safe and fast formatting C++ library
description: |
    {fmt} is an open-source formatting library for C++. It can be used as a safe and fast alternative to (s)printf and IOStreams.
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
