name       : vtm
version    : 0.9.9t
release    : 12
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.9.9t.tar.gz : 23d6ea2703297f403886332c5aab37e9b28fc1659d9973eee9601609d62c4453
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    cd src
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    cd src
    %ninja_build
install    : |
    cd src
    %ninja_install
