name       : vtm
version    : 0.9.99.11
release    : 25
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.11.tar.gz : 4c6e7d6dffa9052a2092c2c2b0f02b40cbe977e4e24654bb1c9ca15af208717b
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
