name       : vtm
version    : 0.9.99.07
release    : 22
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.07.tar.gz : 1bd2bdf67a4bdd83870322887dc14c3ba915aacdf76992852515abcf584d5260
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
