name       : vtm
version    : 0.9.99.10
release    : 24
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.10.tar.gz : c4d3e98dc7149da1a8b4902b3b745826756e0fc1006f1a9725e0045d166b7d10
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
