name       : vtm
version    : 0.9.99.58
release    : 31
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.58.tar.gz : 05e410529413b7405ee15574c22f7ce3d210a0d3797bdfa1d30e365650aeeb9a
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
