name       : vtm
version    : 0.9.99.04
release    : 22
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.04.tar.gz : 6af3cdd2bdb145c024cfc912e16cb2e5ed9769138a7c2824400c53f02b0245d8
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
