name       : vtm
version    : 9.6e
release    : 6
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.9.6e.tar.gz : 8f1cb49c0ecb0254c2dcff352424047095206d0ba5d0f9f95662bd6a6eefab59
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    cd src
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    cd src
    %ninja_build
install    : |
    cd src
    %ninja_install
