name       : vtm
version    : 0.9.72
release    : 18
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.72.tar.gz : 2f7d1f8d59f58801ca3694e2295a4677d61612f9fd35f876ba50421250a20d91
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
