name       : vtm
version    : 0.9.81
release    : 19
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.81.tar.gz : fff8f49162ebd3af946e032b05c7cf375e7bb8ff19cd00401c1827a6179f562b
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
