name       : vtm
version    : 0.9.99.49
release    : 29
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.49.tar.gz : 7fd941089f68531e77bd25eb45cd180dbd6eff9f4732876441483e9e00b13496
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
