name       : vtm
version    : 0.9.99.14
release    : 27
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.14.tar.gz : 7dfe88a4176c18c3c57748e8af72a1e4786a40a92c533e323267add473345b59
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
