name       : vtm
version    : 2025.07.25
release    : 37
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v2025.07.25.tar.gz : d4bc397d6a3eea2be71b2e8de519e5abd815184845800dac546902b156a42510
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
networking : yes
description: |
    Terminal multiplexer with window manager and session sharing
builddeps  :
    - pkgconfig(libinput)
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
