name       : vtm
version    : 0.9.99.71
release    : 34
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.71.tar.gz : 1d64e099c9d96adbe39c0a6ead0715f54bb77ae056ef929dfdcd13b3ac3c1d17
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
networking : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
