name       : vtm
version    : 0.9.9u
release    : 13
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.9.9u.tar.gz : c0d8d47b7dd9e722264b2a8af237fad888734d893081147d06585b9e14df3e33
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
