name       : vtm
version    : 0.7.4
release    : 1
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.7.4.tar.gz : efdf513e449cc2f66e12d3a9d5e52cf3ae8b2a5c9f361ec1a367e5ec74b4e034
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    cd src
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    cd src
    %ninja_build
install    : |
    cd src
    %ninja_install
