name       : vtm
version    : 0.9.91
release    : 21
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.91.tar.gz : c197bb01e401d88073455455ed5c72097b5f0a2c00d1da646b6e89324237bbeb
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
