name       : vtm
version    : 0.7.5
release    : 2
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.7.5.tar.gz : 2cf7e3fdd38bdc262db5f8ab8c06381756065201637eb6d070a8235a7ff7a957
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    cd src
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    cd src
    %ninja_build
install    : |
    cd src
    %ninja_install
