name       : vtm
version    : 0.9.9e
release    : 10
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.9.9e.tar.gz : 871e62595eede0a976f61f48b2f1ff1538283f503d83044ca520d97f093f5634
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    cd src
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    cd src
    %ninja_build
install    : |
    cd src
    %ninja_install
