name       : vtm
version    : 0.9.50
release    : 17
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.50.tar.gz : fe4545c4206f627654fc7d965ed9984d553439d64690169c4535e6e0ee4e9d6f
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
