name       : vtm
version    : 2025.05.28
release    : 35
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v2025.05.28.tar.gz : 302eced60e7f2517fe8efbe5d658638f6c046e88dee9681204d0a2fb886e4cb3
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
networking : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
