name       : vtm
version    : 0.9.9v.1
release    : 15
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.9.9v.1.tar.gz : 3b5a779e2e2cd77bb82c4d23b9f2ba0c0303825746c28a22bd192070ee320b91
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
