name       : vtm
version    : 0.9.99.35
release    : 28
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.35.tar.gz : b6adff2a81fdedd45e1402c344ba8a1c7aca06bb29782fefdcb8a4242cc8d1c7
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
