name       : vtm
version    : 0.9.37
release    : 16
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.37.tar.gz : 788a10949d412f8dd00abee01dcb07281c4f26aa60f9b845f9ffdfd3c428c27e
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
