name       : vtm
version    : 0.9.99.55
release    : 30
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.55.tar.gz : e37882a8a81956c64d6e1c4bb5b4c0526539f18ad519b2c5f84173ee480ab77e
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
