name       : vtm
version    : 0.9.9v
release    : 14
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.9.9v.tar.gz : e533cab2f5986eae5df60f3fd49a1019dee67c6aa1b8b60076ba2f562cf525c3
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
