name       : vtm
version    : 0.8.0
release    : 4
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.8.0.tar.gz : da7ba77eb393e816c01b564a8c38a65ed9aaf7d21aed024ea6842b507aed8919
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    cd src
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    cd src
    %ninja_build
install    : |
    cd src
    %ninja_install
