name       : vtm
version    : 0.9.0
release    : 5
source     :
    - https://github.com/netxs-group/vtm/archive/refs/tags/v0.9.0.tar.gz : ebaaf2542e26d4b7ef5aad91ece9739b92ede2f8238ea37233e485ceb8e4afcd
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    cd src
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    cd src
    %ninja_build
install    : |
    cd src
    %ninja_install
