name       : vtm
version    : 0.9.99.69
release    : 33
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v0.9.99.69.tar.gz : 962e6265fba6889161f0820695dc21ce0c9fca1841a63b60e5189a044bb97b76
homepage   : https://github.com/netxs-group/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
networking : yes
description: |
    Terminal multiplexer with window manager and session sharing
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
