name       : vtm
version    : 2025.11.13
release    : 39
source     :
    - https://github.com/directvt/vtm/archive/refs/tags/v2025.11.13.tar.gz : 42b6fd6528aa7259b8cf8ec67c2a3e4a86719d452545aed2981f9c98800022a3
homepage   : https://github.com/directvt/vtm
license    : MIT
component  : system.utils
summary    : Terminal multiplexer with window manager and session sharing
clang      : yes
networking : yes
description: |
    Terminal multiplexer with window manager and session sharing
builddeps  :
    - pkgconfig(libinput)
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
