name       : boinc-client
version    : 7.14.2
release    : 1
source     :
    - https://github.com/BOINC/boinc/archive/client_release/7.14/7.14.2.tar.gz : 970aedb9e25afa20be67f125ab05435df8eb2e66a3ac30ad316c54085e397c88
license    : GPL-3.0-only
component  : office.scientific
summary    : BOINC client
description: |
    BOINC client
builddeps  :
    - pkgconfig(libnotify)
    - pkgconfig(xcb)
    - pkgconfig(xcb-atom)
    - wxwidgets-devel
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(libcurl)
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(freeglut)

rundeps    : 
    - wxwidgets

setup      : |
    %configure \
    --disable-silent-rules \
    --enable-dynamic-client-linkage \
    --disable-server \
    --disable-fcgi \
    --enable-unicode \
    --with-wx-config=/usr/bin/wx-config \
    --with-ssl \
    --with-x \
    DOCBOOK2X_MAN='/usr/bin/db2x_xsltproc -s man $< -o $(patsubst %.xml,%.mxml,$<); db2x_manxml $(patsubst %.xml,%.mxml,$<); echo' \
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr