name       : boinc-client
version    : 7.14.2
release    : 1
source     :
    - https://github.com/BOINC/boinc/archive/client_release/7.14/7.14.2.tar.gz : 970aedb9e25afa20be67f125ab05435df8eb2e66a3ac30ad316c54085e397c88
license    : GPL-3.0-only
component  : office.scientific
summary    : BOINC client
description: |
    BOINC client
builddeps  :
    - pkgconfig(libnotify)
    - pkgconfig(xcb)
    - pkgconfig(xcb-atom)
    - wxwidgets2.8-devel
    - wxwidgets-devel
    - pkgconfig(openssl)
    - kgconfig(sqlite3)
    - pkgconfig(libcurl)
    - pkgconfig(freeglut)

setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
