name       : boinc-client
version    : 7.16.3
release    : 2
source     :
    - https://github.com/BOINC/boinc/archive/client_release/7.16/7.16.3.tar.gz : 622ce3335a01ef30add4813c0cc7b65cffcaa5500a7f58f77748d0dbc80e6b06
license    : GPL-3.0-only
component  : office.scientific
summary    : BOINC client
description: |
    BOINC client
builddeps  :
    - pkgconfig(libnotify)
    - pkgconfig(xcb)
    - pkgconfig(xcb-atom)
    - wxwidgets2.8-devel
    - wxwidgets-devel
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(libcurl)
    - pkgconfig(freeglut)

setup      : |
    %configure
    --disable-silent-rules \
    --enable-dynamic-client-linkage \
    --disable-server \
    --disable-fcgi \
    --enable-unicode \
    --with-wx-config=/usr/bin/wx-config-2.8 \
    --with-ssl \
    --with-x \
    STRIP=: \
    DOCBOOK2X_MAN=/usr/bin/db2x_docbook2man \
    CXXFLAGS=$(pkg-config gtk+-x11-3.0 --cflags --libs) -DNDEBUG
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr


    <BS>https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/boinc
