name       : wayland-mako
version    : '1.6'
release    : 2
source     :
    - https://github.com/emersion/mako/archive/refs/tags/v1.6.tar.gz : 9f43cba9e1b43c69be8c9e4a79c358b3cd22153ca3ffb8bf0ee7aa30c59b2fc2
license    : GPL-2.0-or-later
component  : desktop
summary    : Lightweight Wayland notification daemon
description: |
    Lightweight Wayland notification daemon
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libsystemd)
    - pkgconfig(pango)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(scdoc)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
