name       : date
version    : 3.0.1
release    : 1
source     :
    - https://github.com/HowardHinnant/date/archive/refs/tags/v3.0.1.tar.gz : 7a390f200f0ccd207e8cff6757e04817c1a0aec3e327b006b7eb451c57ee3538
license    : MIT
component  : programming.devel
summary    :  A date and time library based on the C++11/14/17 <chrono> header
homepage   : https://github.com/HowardHinnant/date
description: |
     A date and time library based on the C++11/14/17 <chrono> header
builddeps  :
    - tree
setup  : |
    %cmake_ninja -DBUILD_TZ_LIB=ON -DUSE_SYSTEM_TZ_DB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
    
