name       : rymdport
version    : 3.2.0
release    : 2
source     :
    - https://github.com/Jacalz/rymdport/archive/refs/tags/v3.2.0.tar.gz : a630946f5bac0f8eb8dadd4f839e1cef52605b3d0224fc2c9b21b165655fa593
license    : GPL-3.0-or-later
homepage   : https://github.com/Jacalz/wormhole-gui
component  : network.client
summary    : Wormhole-gui is a cross-platform graphical interface for magic-wormhole
description: |
    Wormhole-gui is a cross-platform graphical interface for magic-wormhole that lets you easily share files, folders and text between devices. It uses the Go implementation of magic-wormhole, called wormhole-william, and compiles statically into a single binary. Wormhole-gui is compatible with the cli applications from both wormhole-william and magic-wormhole.
networking : yes
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
    - golang
build      : |
    # something with ldflags is not working, so skip them
    go build -o rymdport
install    : |
    %make_install
    # Correct icon location, thanks Archbros
    install -Dm00644 "$installdir/usr/share/icons/hicolor/512x512/io.github.jacalz.rymdport.png" "$installdir/usr/share/pixmaps/io.github.jacalz.rymdport.png"   
    install -Dm00644 "$installdir/usr/share/icons/hicolor/scalable/io.github.jacalz.rymdport.svg" "$installdir/usr/share/pixmaps/io.github.jacalz.rymdport.svg"
    rm -rf "$installdir/usr/share/icons"
