name       : rymdport
version    : 3.2.0
release    : 3
source     :
    - https://github.com/Jacalz/rymdport/releases/download/v3.2.0/rymdport-v3.2.0-vendored.tar.xz : e6f01410ac5f8c46caddad21bb14e8cd67241c685be10ffceeb852bc071778d3
license    : GPL-3.0-or-later
homepage   : https://github.com/Jacalz/rymdport
component  : network.client
summary    : Easy encrypted file, folder, and text sharing between devices.
description: |
    Rymdport (formerly wormhole-gui) is a cross-platform application that lets you easily and safely share files, folders, and text between devices. The data is sent securely with end-to-end encryption using the same protocol as magic-wormhole. This means that Rymdport can talk not only to itself, but also to other wormhole clients.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
    - golang
build      : |
    # something with ldflags is not working, so skip them
    go build -trimpath -o rymdport
install    : |
    %make_install
    # Correct icon location, thanks Archbros
    install -Dm00644 "$installdir/usr/share/icons/hicolor/512x512/io.github.jacalz.rymdport.png" "$installdir/usr/share/pixmaps/io.github.jacalz.rymdport.png"   
    install -Dm00644 "$installdir/usr/share/icons/hicolor/scalable/io.github.jacalz.rymdport.svg" "$installdir/usr/share/pixmaps/io.github.jacalz.rymdport.svg"
    rm -rf "$installdir/usr/share/icons"
