name       : verilator
version    : '4.028'
release    : 12
source     :
    - https://www.veripool.org/ftp/verilator-4.028.tgz : 344c859b105eb4d382ab89fbc515fd3bf915dc17bf75f90e918141afac1489e6
license    :
    - LGPL-3.0-only
    - Artistic-2.0
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
