name       : verilator
version    : '4.034'
release    : 14
source     :
    - https://www.veripool.org/ftp/verilator-4.034.tgz : 54ed7b06ee28b5d21f9d0ee98406d29a508e6124b0d10e54bb32081613ddb80b
license    :
    - LGPL-3.0-only
    - Artistic-2.0
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
rundeps    :
    - ccache
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
