name       : nnn
version    : '2.6'
release    : 7
source     :
    - https://github.com/jarun/nnn/archive/v2.6.tar.gz : 17fd3e517308e41065594ffe8dcde348b4d10dea4240699f4708337db48b3e25
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - mediainfo
    - moreutils
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
