name       : fsearch
version    : '0.1'
release    : 2
source     :
    - https://github.com/cboxdoerfer/fsearch/archive/refs/tags/v0.1.tar.gz : 50287fb77e56d2451bd828f207e9a1e33958aea591ec030d47b8b67d4e6f0828
license    : GPL-2.0-or-later
component  : desktop
summary    : FSearch is a fast file search utility, inspired by Everything Search Engine. It is written in C and based on GTK+3.
description: |
    FSearch is a fast file search utility, inspired by Everything Search Engine. It is written in C and based on GTK+3.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(libpcre)
    - autoconf-archive
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
