name       : kanshi
version    : 1.1.0
release    : 1
source     :
    - https://github.com/emersion/kanshi/archive/v1.1.0.tar.gz : f7e782d2b49380aed370213b8d74af9fe806d9dc94b3c19179475f4b18e26566
license    : MIT
component  : desktop
summary    : kanshi allows you to define output profiles for sway that are automatically enabled and disabled on hotplug. For instance, this can be used to turn a laptop's internal screen off when docked.
description: |
    kanshi allows you to define output profiles for sway that are automatically enabled and disabled on hotplug. For instance, this can be used to turn a laptop's internal screen off when docked.
builddeps  :
    - pkgconfig(scdoc) 
    - pkgconfig(wayland-client)
setup      : |
    %patch -p1 < $pkgfiles/0001-remove-scdoc-native.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
