name       : kanshi
version    : 1.3.0
release    : 4
source     :
    - https://git.sr.ht/~emersion/kanshi/archive/v1.3.0.tar.gz : 67a4fe896d97b7fbd3fcc51aab0fae550b4130b2df2b1df2a4d0e8d3221fe604
license    : MIT
homepage   : https://wayland.emersion.fr/kanshi/
component  : desktop
summary    : kanshi allows you to define output profiles for sway that are automatically enabled and disabled on hotplug. For instance, this can be used to turn a laptop's internal screen off when docked.
description: |
    kanshi allows you to define output profiles for sway that are automatically enabled and disabled on hotplug. For instance, this can be used to turn a laptop's internal screen off when docked.
builddeps  :
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
