name       : kanshi
version    : 1.2.0
release    : 2
source     :
    - https://github.com/emersion/kanshi/archive/refs/tags/v1.2.0.tar.gz : 144428b9e79209b853c4b38a5efb6f16d581a2b9cb96e419b3b0a0f5914bcad4
license    : MIT
component  : desktop
summary    : kanshi allows you to define output profiles for sway that are automatically enabled and disabled on hotplug. For instance, this can be used to turn a laptop's internal screen off when docked.
description: |
    kanshi allows you to define output profiles for sway that are automatically enabled and disabled on hotplug. For instance, this can be used to turn a laptop's internal screen off when docked.
builddeps  :
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
