name       : tailscale
version    : 1.32.1
release    : 2
source     :
    - https://github.com/tailscale/tailscale/archive/refs/tags/v1.32.1.tar.gz : c854e4af9b0b7ac4682942bed6ffe364d3126826f9d8c083a169a6aff12a2f3d
license    : BSD-3-Clause
component  : network.clients
summary    : Private WireGuard networks made easy
description: |
    Private WireGuard networks made easy
networking : yes
builddeps  :
    - golang
build      : |
    cd cmd/tailscale
    export GOPATH=$(pwd)
    go build
    cd ../tailscaled
    export GOPATH=$(pwd)
    go build
install    : |
    install -Dm00755 cmd/tailscale/tailscale $installdir/usr/bin/tailscale
    install -Dm00755 cmd/tailscaled/tailscaled $installdir/usr/sbin/tailscaled
    install -Dm00644 cmd/tailscaled/tailscaled.service $installdir/usr/lib/systemd/system/tailscaled.service
    install -Dm00644 cmd/tailscaled/tailscaled.defaults $installdir/etc/default/tailscaled
