name       : seatd
version    : 0.5.0
release    : 1
source     :
    - https://git.sr.ht/~kennylevinsen/seatd/archive/0.5.0.tar.gz : 274b56324fc81ca6002bc1cdd387668dee34a6e1063e5f3896805c3770948988
license    : MIT
component  : system.utils
summary    : A minimal seat management daemon, and a universal seat management library
description: |
    A minimal seat management daemon, and a universal seat management library.
builddeps  :
    - pkgconfig(scdoc)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
