name       : warpinator
version    : 1.8.3
release    : 1
source     :
    - https://github.com/linuxmint/warpinator/archive/1.8.3/warpinator-1.8.3.tar.gz : 1e1e52519301e4913644ae48a588c93f380603ecbfb399f9ba55d575d6cd4a71
homepage   : https://warpinator.com/
license    : GPL-3.0-or-later
component  : networking.clients
summary    : Send and receive files across a local network
description: |
    Send and receive files across a local network
rundeps    :
    - python-grpcio
setup      : |
    %meson_configure \
    -Dbundle-zeroconf=false \
    -Dbundle-grpc=false \
    -Dbundle-landlock=false
build      : |
    %ninja_build
install    : |
    %ninja_install
