name       : vis
version    : 0.7
release    : 1
source     :
    - https://github.com/martanne/vis/releases/download/v0.7/vis-0.7.tar.gz : 359ebb12a986b2f4e2a945567ad7587eb7d354301a5050ce10d51544570635eb
license    : ISC
component  : editor
summary    : Vis aims to be a modern, legacy-free, simple yet efficient editor, combining the strengths of both vi(m) and sam
description: |
    Vis aims to be a modern, legacy-free, simple yet efficient editor, combining the strengths of both vi(m) and sam.
builddeps  :
    - pkgconfig(termkey)
    - pkgconfig(ncursesw)
    - lua-devel
rundep    :
    - lpeg
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
