# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : act
version    : 0.2.84
release    : 2
source     :
    - https://github.com/nektos/act/archive/refs/tags/v0.2.84.tar.gz : da58b74d03b2cd21df81aeb054c2792054d6cf9d4c3171e98440fde9becb01fa
homepage   : https://github.com/nektos/act
license    : MIT
component  : proramming.tools
summary    : Run your GitHub Actions locally
description: |
    Run your GitHub Actions locally
networking : true
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$(VERSION)" -o act
install    : |
    install -Dm00755 act $installdir/usr/bin/act
