name       : zola
version    : 0.21.0
release    : 3
source     :
    - https://github.com/getzola/zola/archive/refs/tags/v0.21.0.tar.gz : bbfbc0496cf6612b6030c6d97b0fd2567f5ec41e251f8874b6c9ccda4c8149d4
license    : MIT
homepage   : https://www.getzola.org/
component  : programming
summary    : A fast static site generator in a single binary with everything built-in.
description: |
    A fast static site generator in a single binary with everything built-in.
networking : yes
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |-
    %cargo_install
