name       : zola
version    : 0.18.0
release    : 2
source     :
    - https://github.com/getzola/zola/archive/refs/tags/v0.18.0.tar.gz : c0e1711a68bc005c2e0ecc76a468f3459739c9e54af34850cb725d04391e19b5
license    : MIT
homepage   : https://www.getzola.org/
component  : programming
summary    : A fast static site generator in a single binary with everything built-in.
description: |
    A fast static site generator in a single binary with everything built-in.
networking : yes
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install