# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : pastel
version    : 0.10.0
release    : 1
source     :
    - https://github.com/sharkdp/pastel/archive/refs/tags/v0.10.0.tar.gz : 7848cd6d2ad8db6543b609dece7c9c28b4720c09fb13aeb204dd03d152159dd2
homepage   : https://github.com/sharkdp/pastel
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : A command-line tool to generate, analyze, convert and manipulate colors
description: |
    A command-line tool to generate, analyze, convert and manipulate colors
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
