# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : pastel
version    : 0.12.0
release    : 2
source     :
    - https://github.com/sharkdp/pastel/archive/refs/tags/v0.12.0.tar.gz : 2903853f24d742fe955edd9bea17947eb8f3f44000a8ac528d16f2ea1e52b78b
homepage   : https://github.com/sharkdp/pastel
license    :
    - Apache-2.0
    - MIT
component  : system.utils
summary    : A command-line tool to generate, analyze, convert and manipulate colors
description: |
    A command-line tool to generate, analyze, convert and manipulate colors
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
