name       : oil
version    : 0.24.0
release    : 2
source     :
    - https://www.oilshell.org/download/oil-0.24.0.tar.gz : f199f5384e72c53eeb8a159ee7ac1b92819adc13a6dc5644ccae33e7ceaa9c72
homepage   : https://www.oilshell.org
license    : Apache-2.0
component  : system.utils
summary    : Oil is a new Unix shell. It is our upgrade path from bash to a better language and runtime
description: |
    Oil is a new Unix shell. It is our upgrade path from bash to a better language and runtime
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
