name       : wofi
version    : '1.3'
release    : 4
source     :
    - https://hg.sr.ht/~scoopta/wofi/archive/v1.3.tar.gz : 7644e4e995bc027b7f3f411ceda82b3e2a72a4a424f6193663c27bbf00f23067
license    : GPL-3.0-or-later
homepage   : https://hg.sr.ht/~scoopta/wofi
component  : desktop
summary    : Wofi is a launcher/menu program for wlroots based wayland compositors such as sway
description: |
    Wofi is a launcher/menu program for wlroots based wayland compositors such as sway
builddeps  :
    - pkgconfig(wayland-protocols)
    - pkgconfig(gtk+-wayland-3.0)

setup      : |
    %meson_configure
build      : |
    %ninja_install
install    : |
    %ninja_install
