name       : wofi
version    : 1.2.4
release    : 3
source     :
    - https://hg.sr.ht/~scoopta/wofi/archive/v1.2.4.tar.gz : f71cfa92a8e68c5170fae16ca3e6f3f7b9c5f4391c3fed5115bfc774be8ade38
license    : GPL-3.0-or-later
component  : desktop
summary    : Wofi is a launcher/menu program for wlroots based wayland compositors such as sway
description: |
    Wofi is a launcher/menu program for wlroots based wayland compositors such as sway
builddeps  :
    - pkgconfig(wayland-protocols)
    - pkgconfig(gtk+-wayland-3.0)

setup      : |
    %meson_configure
build      : |
    %ninja_install
install    : |
    %ninja_install
