name       : wofi
version    : 1.2.4
release    : 3
source     :
    - https://github.com/davidjharder/solus-builds/raw/master/wofi/files/v1.2.3.tar.gz : c93371c38cddfa794594d85bc097a03585c28ef8e47c0fd0f820231ee628a64b
license    : GPL-3.0-or-later
component  : desktop
summary    : Wofi is a launcher/menu program for wlroots based wayland compositors such as sway
description: |
    Wofi is a launcher/menu program for wlroots based wayland compositors such as sway
builddeps  :
    - pkgconfig(wayland-protocols)
    - pkgconfig(gtk+-wayland-3.0)

setup      : |
    %meson_configure
build      : |
    %ninja_install
install    : |
    %ninja_install
