name       : python-pikepdf
version    : 1.9.0
release    : 1
source     :
    - https://github.com/pikepdf/pikepdf/archive/v1.9.0.tar.gz : c8bedaaf43188b057b4b525e1328896d3961fdec694c0dfe796857c35bfd7ac7
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    A Python library for reading and writing PDF, powered by qpdf
builddeps   :
    - pkgconfig(libqpdf)
    - pybind11
    - python-setuptools
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
