name       : jsoncpp
version    : 1.9.4
release    : 5
source     :
    - https://github.com/open-source-parsers/jsoncpp/archive/refs/tags/1.9.4.tar.gz : e34a628a8142643b976c7233ef381457efad79468c67cb1ae0b83a33d7493999
license    : MIT
component  : programming.library
summary    : A C++ library for interacting with JSON.
description: |
    JsonCpp is a C++ library that allows manipulating JSON values, including serialization and deserialization to and from strings. It can also preserve existing comment in unserialization/serialization steps, making it a convenient format to store user input files.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
