name       : grim
version    : 1.3.1
release    : 1
source     :
    - https://github.com/emersion/grim/archive/v1.3.1.tar.gz : b1ab720b5dbcd560cfa34bbd7e0cbe85330f701c471b12e2489dfec15bcf216e
license    : MIT
component  : desktop
summary    : Grab images from a Wayland compositor. Works great with slurp and with sway.
description: |
    Grab images from a Wayland compositor. Works great with slurp and with sway.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libjpeg)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
