name       : grim
version    : 1.3.2
release    : 2
source     :
    - https://github.com/emersion/grim/archive/refs/tags/v1.3.2.tar.gz : 42c2952e98389506156c08e40e0c37afdc2ec5ef4d55a5a4febde6acdac4d1c8
license    : MIT
component  : desktop
summary    : Grab images from a Wayland compositor. Works great with slurp and with sway.
description: |
    Grab images from a Wayland compositor. Works great with slurp and with sway.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libjpeg)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
