name       : xxhash
version    : 0.8.1
release    : 8
source     :
    - https://github.com/Cyan4973/xxHash/archive/v0.8.1.tar.gz : 3bb6b7d6f30c591dd65aaaff1c8b7a5b94d81687998ca9400082c739a690436c
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
component  : programming.library
summary    : Extremely fast hash algorithm
description: |
    xxHash is an Extremely fast Hash algorithm, running at RAM speed limits. It successfully completes the SMHasher test suite which evaluates collision, dispersion and randomness qualities of hash functions. Code is highly portable, and hashes are identical on all platforms (little / big endian).
build      : |
    if [[ ! -z "${AVX2BUILD}" ]]; then
      XXH_AVX2=1 DISPATCH=1 %make
    else
      XXH_SSE2=1 DISPATCH=1 %make
    fi
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm $installdir/%libdir%/libxxhash.a
