name       : yofi
version    : 0.2.0
release    : 2
source     :
    - https://github.com/l4l/yofi/archive/refs/tags/0.2.0.tar.gz : 343541731f5fe771e47e4516eb95dd057e7d3c0837f7ba7e529fc663f77ba074
license    : MIT
homepage   : https://github.com/l4l/yofi
component  : desktop
summary    : yofi is a minimalistic menu for Wayland-based compositors
description: |
    yofi is a minimalistic menu for Wayland-based compositors
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/yofi $installdir/usr/bin/yofi
