name       : transifex-cli
version    : 1.6.13
release    : 2
source     :
    - https://github.com/transifex/cli/archive/refs/tags/v1.6.13.tar.gz : d96b2d0e00538f6193ad99245e9ee346a0339734d24673c9f5e991ade105b82a
homepage   : https://github.com/transifex/cli
license    : Apache-2.0
component  : sytem.utils
summary    : The Transifex command-line client
description: |
    The Transifex command-line client
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 $workdir/bin/tx $installdir/usr/bin/tx
