name       : transifex-cli
version    : 1.6.17
release    : 3
source     :
    - https://github.com/transifex/cli/archive/refs/tags/v1.6.17.tar.gz : 759320acd621991046533089bb77320202853cc97b860ab7783040d0e4d5e34f
homepage   : https://github.com/transifex/cli
license    : Apache-2.0
component  : sytem.utils
summary    : The Transifex command-line client
description: |
    The Transifex command-line client
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 $workdir/bin/tx $installdir/usr/bin/tx
