name       : solus-onboard
version    : 0.1.1
release    : 2
source     :
    - https://github.com/davidjharder/solus-onboard/archive/refs/tags/v0.1.1.tar.gz : 95e627da721065e4af486068d4c1d999c875e9b85dbe41413b992018a1e3594a
license    : MIT
component  : programming.tools
summary    : An experiment for on-boarding
description: |
    An experiment for on-boarding
rundeps    :
    - arcanist
    - git
    - solbuild-config-local-unstable

install    : |
    install -Dm00755 $workdir/iamagiraffe.sh $installdir/usr/bin/iamagiraffe
    install -Dm00755 $pkgfiles/onboard-me.sh $installdir/usr/bin/onboard-me
