name       : lua-lgi
version    : 0.9.2
release    : 1
source     :
    - https://github.com/pavouk/lgi/archive/0.9.2.tar.gz : cfc4105482b4730b3a40097c9d9e7e35c46df2fb255370bdeb2f45a886548c4f
license    : MIT
component  : programming.library
summary    : LGI is gobject-introspection based dynamic Lua binding to GObject based libraries. It allows using GObject-based libraries directly from Lua.
description: |
    LGI is gobject-introspection based dynamic Lua binding to GObject based libraries. It allows using GObject-based libraries directly from Lua.
builddeps  :
    - lua-devel
#setup      : |
#    %configure
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
