name       : megasync
version    : 4.5.0.0
release    : 2
source     :
    - https://github.com/meganz/MEGAsync/archive/refs/tags/v4.5.0.0_Win.tar.gz : f4bafecf203d75c837a90819d74f85baac1c8476f10afbb48a291c6fd5a4d0b5
    - https://github.com/meganz/sdk/archive/refs/tags/v3.8.8.tar.gz : 540c576b9e4459a2d07d33ea300f510d72608624cb9635f44fd0681092e84470
license    : MEGA LIMITED CODE REVIEW LICENCE
component  : network.clients
summary    : Sync your files to your Mega account.
description: |
    Easy automated syncing between your computers and your MEGA Cloud Drive.
builddeps  :
    - pkgconfig(libcares)
    - pkgconfig(libcryptopp)
    - pkgconfig(libcurl)
    - pkgconfig(libmediainfo)
    - pkgconfig(libraw)
    - pkgconfig(libsodium)
    - pkgconfig(libuv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sqlite3)
    - pkgconfig(xcb)
    - bzip2-devel
    - freeimage-devel
setup      : |
    cd $workdir/src/MEGASync/mega
    tar -xf $sources/v3.8.8.tar.gz --strip 1 -C .
    %autogen
    cd $workdir/src
    %configure
build      : |
    cd $workdir/src
    %qmake MEGA.pro
    lrelease MEGASync/MEGASync.pro
    %make
install    : |
    install -Dm 755 $workdir/src/MEGASync/megasync $installdir/usr/bin/megasync
    install -Dm 644 $workdir/src/MEGASync/platform/linux/data/megasync.desktop $installdir/usr/share/applications/megasync.desktop
    for size in 16x16 32x32 48x48 128x128 256x256
    do
    install -Dm 644 $workdir/src/MEGASync/platform/linux/data/icons/hicolor/$size/apps/mega.png $installdir/usr/share/icons/hicolor/$size/apps/mega.png
    done
