name       : python-slugify
version    : 4.0.1
release    : 1
source     :
    - https://github.com/un33k/python-slugify/archive/4.0.1.tar.gz : dc6a6dc0c0f1c1492d576b0862c9a50a457853fd86b42caa7f24360dfa3204c4
license    : MIT
component  : programming.python
summary    : Best attempt to create slugs from unicode strings while keeping it DRY.
description: |
    Best attempt to create slugs from unicode strings while keeping it DRY.
networking : yes
build      : |
    %python3_setup
install    : |
    %python3_install
