name       : python-pykwalify
version    : 1.7.0
release    : 1
source     :
    - https://github.com/Grokzen/pykwalify/releases/download/1.7.0/pykwalify-1.7.0.tar.gz : 7e8b39c5a3a10bc176682b3bd9a7422c39ca247482df198b402e8015defcceb2
homepage   : https://github.com/Grokzen/pykwalify
license    : MIT
component  : programming.python
summary    : AML/JSON validation library
description: |
    Python YAML/JSON schema validation library
rundeps    :
    - python-dateutil
    - python-docopt
    - python-ruamel-yaml
build      : |
    %python3_setup
install    : |
    %python3_install
