name       : autorestic
version    : 1.6.2
release    : 3
source     :
    - https://github.com/cupcakearmy/autorestic/archive/refs/tags/v1.6.2.tar.gz : 3ad6e2e9bb7ad8b48c1f4405995ed757cb3d6707ec141e12969b2f14e8240459
license    : Apache-2.0
homepage   : https://autorestic.vercel.app/
component  : system.utils
summary    : Config driven, easy backup cli for restic
description: |
    Config driven, easy backup cli for restic
networking : yes
builddeps  :
    - golang
rundeps    :
    - restic
build      : |
    go build -ldflags "-X main.version=$version" -o autorestic
install    : |
    install -Dm00755 $workdir/autorestic $installdir/usr/bin/autorestic
