name       : autorestic
version    : 1.7.1
release    : 4
source     :
    - https://github.com/cupcakearmy/autorestic/archive/refs/tags/v1.7.1.tar.gz : 89ffb11c14eb02bcc66427517a43a42a7e73ea359b579b8c2047c95ce5f9a8d8
license    : Apache-2.0
homepage   : https://autorestic.vercel.app/
component  : system.utils
summary    : Config driven, easy backup cli for restic
description: |
    Config driven, easy backup cli for restic
networking : yes
builddeps  :
    - golang
rundeps    :
    - restic
build      : |
    go build -ldflags "-X main.version=$version" -o autorestic
install    : |
    install -Dm00755 $workdir/autorestic $installdir/usr/bin/autorestic
